name: Package

on:
  workflow_dispatch:
  push:
    tags:
      - v*.*.*


jobs:

  sdist:
    runs-on: ubuntu-latest
    name: Build source distribution
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        submodules: true
    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'
    - name: Install build requirements
      run: python -m pip install -U setuptools pip
    - name: Build source distribution
      run: python setup.py sdist
    - name: Store built source distribution
      uses: actions/upload-artifact@v2
      with:
        name: dist
        path: dist/*

  test-sdist:
    runs-on: ubuntu-latest
    name: Test source distribution
    needs:
    - sdist
    steps:
    - name: Setup Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'
    - name: Download source distribution
      uses: actions/download-artifact@v2
      with:
          name: dist
          path: dist/
    - name: Update pip to latest version
      run: python -m pip install -U pip setuptools wheel
    - name: Install source distribution
      run: python -m pip install --no-binary btyper3 --find-links=dist btyper3
    - name: Check install worked
      run: btyper3 --version

  upload:
    environment: PyPI
    runs-on: ubuntu-latest
    name: Upload
    needs:
    - sdist
    - test-sdist
    steps:
    - name: Download distributions
      uses: actions/download-artifact@v2
      with:
          name: dist
          path: dist
    - name: Publish distributions to PyPI
      if: "startsWith(github.ref, 'refs/tags/v')"
      uses: pypa/gh-action-pypi-publish@master
      with:
        user: __token__
        password: ${{ secrets.PYPI_API_TOKEN }}
        skip_existing: false

  # release:
  #   environment: GitHub Releases
  #   runs-on: ubuntu-latest
  #   if: "startsWith(github.ref, 'refs/tags/v')"
  #   name: Release
  #   needs: upload
  #   steps:
  #   - name: Checkout code
  #     uses: actions/checkout@v1
  #     with:
  #       submodules: true
  #   - name: Release a Changelog
  #     uses: rasmus-saks/release-a-changelog-action@v1.0.1
  #     with:
  #       github-token: '${{ secrets.GITHUB_TOKEN }}'
